// love it
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0022:Should dispose object", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.Save.StartSaveTimer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0022:Should dispose object", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.CheckAutoReloadFile.Run(System.String)")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BP_Essentials.IdListObject.items")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BP_Essentials.Item.gameid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BP_Essentials.Item.id")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:BP_Essentials.Item.name")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.SvAddCrime(SvPlayer,System.Byte@,ShEntity@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.TransferItem(ShPlayer,System.Byte@,System.Int32@,System.Int32@,System.Boolean@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.Damage(SvPlayer,DamageIndex@,System.Single@,ShPlayer@,UnityEngine.Collider@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.SpawnBot(SvPlayer,UnityEngine.Vector3@,UnityEngine.Quaternion@,Place@,WaypointNode@,ShPlayer@,ShTransport@,ShPlayer@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.HitEffect(ShRestraint,ShEntity@,ShPlayer@,UnityEngine.Collider@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.Commands.Afk.Run(SvPlayer,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.Commands.Atm.Run(SvPlayer,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.Commands.Home.Run(SvPlayer,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.Commands.TpaAccept.Run(SvPlayer,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.Commands.TpaDeny.Run(SvPlayer,System.String)")]