// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.Damage(SvPlayer,DamageIndex@,System.Single@,ShPlayer@,UnityEngine.Collider@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0030:Suggests using the class declaring a static function when calling it", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.HitEffect(ShRetainer,ShEntity@,ShPlayer@,UnityEngine.Collider@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.HitEffect(ShRetainer,ShEntity@,ShPlayer@,UnityEngine.Collider@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.SpawnBot(SvPlayer,UnityEngine.Vector3@,UnityEngine.Quaternion@,Place@,WaypointNode@,ShTransport@,ShPlayer@,System.Byte@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.SpawnBot(SvPlayer,UnityEngine.Vector3@,UnityEngine.Quaternion@,Place@,WaypointNode@,ShTransport@,ShPlayer@,System.Byte@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Common Practices and Code Improvements", "RECS0030:Suggests using the class declaring a static function when calling it", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.SvBan(SvPlayer,System.Int32@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.Damage(SvPlayer,DamageIndex@,System.Single@,ShPlayer@,UnityEngine.Collider@)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "<Pending>", Scope = "member", Target = "~M:BP_Essentials.EssentialsMethodsPlugin.HitEffect(ShRetainer,ShEntity@,ShPlayer@,UnityEngine.Collider@)~System.Boolean")]